spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      hibernate.query.in_clause_parameter_padding: true
      #hibernate.query.plan_cache_max_size: 2048
      #hibernate.query.plan_parameter_max_size: 128
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_item_db
    username: root
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  kafka:
    bootstrap-servers: localhost:29092

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    eureka-server-port: 8761
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka
    healthcheck:
      enabled: true