spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_item_db   #jdbc:h2:~/test_item_db
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create
        show_sql: true
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual