spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://mysql:3306/account_service
  cloud:
    discovery:
      client:
        simple:
          local:
            host: api-gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:${eureka.client.eureka-server-port}/eureka