server:
  port: 0

spring:
  application:
    name: item-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.query.in_clause_parameter_padding: true
      #hibernate.query.plan_cache_max_size: 2048
      #hibernate.query.plan_parameter_max_size: 128
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/item_service
    username: root
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.nayoung.itemservice.kafka.dto.OrderDtoSerializer
    consumer:
      group-id: orderServiceGroup
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer:
        - org.apache.kafka.common.serialization.LongSerializer
        - com.nayoung.itemservice.kafka.dto.OrderDtoDeserializer
    streams:
      application-id: item_application

logging:
  level:
    com.nayoung.itemservice: DEBUG

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8061/eureka