spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_item_db
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql

  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka