server:
  port: 0

spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/order_service
    username: root
    password: 1234
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.nayoung.orderservice.messagequeue.OrderDtoSerializer
    consumer:
      group-id: orderServiceGroup
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: com.nayoung.orderservice.messagequeue.OrderDtoDeserializer
    streams:
      application-id: order_application
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    com.nayoung.orderservice: DEBUG

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka