spring:
  datasource:
    url: jdbc:mysql://mysql:3306/item_service
  data:
    redis:
      url: redis:${spring.data.redis.port}
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://service-disconvery:${eureka.client.eureka-server-port}/eureka