spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      hibernate.query.in_clause_parameter_padding: true
#      hibernate.query.plan_cache_max_size: 2048
#      hibernate.query.plan_parameter_max_size: 128
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_order_db
    username: root
  kafka:
    bootstrap-servers: localhost:29092
  cloud:
    discovery:
      client:
        simple:
          local:
            host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka