spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: false
  datasource:
    url: jdbc:mysql://localhost:3306/test_item_service
  sql:
    init:
      mode: always
      data-locations: classpath:db/data.sql
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka