spring:
  datasource:
    url: jdbc:mysql://mysql:3306/order_service
  data:
    redis:
      url: redis:${spring.data.redis.port}
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    discovery:
      client:
        simple:
          local:
            host: api-gateway-service

eureka:
  instance:
    hostname: service-discovery
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka
    healthcheck:
      enabled: true